server:
  port: 8085
spring:
  application:
    name: quartz_email_service
  datasource:
    url: jdbc:mysql://localhost/quartz_demo
    username: cs544
    password: 201511
    driverClassName: com.mysql.cj.jdbc.Driver
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
